version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    volumes:
      - ./backend:/app
      - ./session:/app/session
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
